name: Build macOS Application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-macos:
    runs-on: macos-13

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          submodules: recursive  # 递归拉取子模块

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.bash_profile
          eval "$(/opt/homebrew/bin/brew shellenv)"

      - name: Install Dependencies
        run: |
          brew update
          brew install qt
          brew install cmake # 如果使用cmake，则需要安装
          brew install create-dmg # 安装用于创建dmg的工具
          # 如果有其他依赖，请在这里添加

      - name: Set up Qt environment variables
        run: |
          echo "QT_DIR=$(brew --prefix qt)" >> $GITHUB_ENV
          echo "$QT_DIR/bin" >> $GITHUB_PATH

      - name: Build Project
        env:
          QT_DIR: ${{ env.QT_DIR }}
          MACOSX_DEPLOYMENT_TARGET: 13.0  # 设置最低部署目标版本为macOS 13.0

        run: |
          mkdir build && cd build
          qmake ../moonlight-qt.pro
          make -j$(sysctl -n hw.ncpu)

      - name: Package Application
        run: |
          cd build
          macdeployqt app/Moonlight.app

      - name: Create DMG Package
        run: |
          cd build
          mkdir -p installer
          create-dmg \
            --volname "Moonlight Installer" \
            --volicon "app/Moonlight.app/Contents/Resources/moonlight.icns" \
            --window-pos 200 120 \
            --window-size 600 400 \
            --icon-size 100 \
            --app-drop-link 420 205 \
            --icon "Moonlight.app" 180 205 \
            "installer/Moonlight.dmg" \
            "app/Moonlight.app"

      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: moonlight-qt-macOS
          path: build/installer/Moonlight.dmg
