name: Build macOS Application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          submodules: recursive  # 添加此行，递归拉取子模块

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.bash_profile
          eval "$(/opt/homebrew/bin/brew shellenv)"

      - name: Install Dependencies
        run: |
          brew update
          brew install qt
          brew install cmake # 如果使用cmake，则需要安装
          # 如果有其他依赖，请在这里添加

      - name: Set up Qt environment variables
        run: |
          echo "QT_DIR=$(brew --prefix qt)" >> $GITHUB_ENV
          echo "$QT_DIR/bin" >> $GITHUB_PATH

      - name: Build Project
        env:
          QT_DIR: ${{ env.QT_DIR }}
        run: |
          mkdir build && cd build
          qmake ../moonlight-qt.pro
          make -j$(sysctl -n hw.ncpu)

      - name: Package Application
        run: |
          cd build
          macdeployqt moonlight-qt.app

      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: moonlight-qt-macOS
          path: build/moonlight-qt.app
